const router = require('express').Router();
const { body, validationResult } = require('express-validator');
const Reminder = require('../models/Reminder');
const auth = require('../middleware/auth');
const { runMLAnalysis } = require('./ml');

// GET /api/reminders
router.get('/', auth, async (req, res) => {
  try {
    const { status, deviceId, priority } = req.query;
    const filter = { user: req.user._id };
    if (status)   filter.status = status;
    if (deviceId) filter.device = deviceId;
    if (priority) filter.priority = priority;

    const reminders = await Reminder.find(filter)
      .populate('device', 'name brand model category image customCategory displayCategory')
      .sort('dueDate');

    res.json({ reminders });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// POST /api/reminders — manual creation
router.post('/', auth, [
  body('title').trim().notEmpty(),
  body('device').notEmpty().withMessage('Device is required'),
  body('dueDate').isISO8601().withMessage('Valid due date required')
], async (req, res) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) return res.status(400).json({ errors: errors.array() });
  try {
    const { title, description, device, taskType, priority, dueDate, repeatEvery, repeatUnit } = req.body;
    const reminder = await Reminder.create({
      user: req.user._id,
      title, description, device, taskType,
      priority, dueDate, repeatEvery, repeatUnit,
      autoGenerated: false,
      source: 'manual'
    });
    await runMLAnalysis(reminder._id);
    const populated = await reminder.populate('device', 'name brand model category image customCategory displayCategory');
    res.status(201).json({ reminder: populated });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// PATCH /api/reminders/:id/complete — mark done + auto-reschedule repeating
router.patch('/:id/complete', auth, async (req, res) => {
  try {
    const reminder = await Reminder.findOne({ _id: req.params.id, user: req.user._id });
    if (!reminder) return res.status(404).json({ error: 'Reminder not found' });

    reminder.status = 'Done';
    reminder.completedAt = new Date();

    // Auto-reschedule if it repeats
    if (reminder.repeatEvery > 0) {
      const nextDate = new Date(reminder.dueDate);
      if (reminder.repeatUnit === 'weeks')       nextDate.setDate(nextDate.getDate() + reminder.repeatEvery * 7);
      else if (reminder.repeatUnit === 'months') nextDate.setMonth(nextDate.getMonth() + reminder.repeatEvery);
      else                                       nextDate.setDate(nextDate.getDate() + reminder.repeatEvery);

      const next = await Reminder.create({
        user:          reminder.user,
        device:        reminder.device,
        title:         reminder.title,
        description:   reminder.description,
        taskType:      reminder.taskType,
        priority:      reminder.priority,
        dueDate:       nextDate,
        repeatEvery:   reminder.repeatEvery,
        repeatUnit:    reminder.repeatUnit,
        autoGenerated: reminder.autoGenerated,
        source:        reminder.source
      });
      await runMLAnalysis(next._id);
    }

    await reminder.save();
    res.json({ reminder });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// PATCH /api/reminders/:id — general update
router.patch('/:id', auth, async (req, res) => {
  try {
    const reminder = await Reminder.findOneAndUpdate(
      { _id: req.params.id, user: req.user._id },
      { ...req.body, emailSent: false },
      { new: true }
    ).populate('device', 'name brand model category image customCategory displayCategory');
    if (!reminder) return res.status(404).json({ error: 'Reminder not found' });
    res.json({ reminder });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// DELETE /api/reminders/:id
router.delete('/:id', auth, async (req, res) => {
  try {
    await Reminder.findOneAndDelete({ _id: req.params.id, user: req.user._id });
    res.json({ message: 'Reminder deleted' });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// GET /api/reminders/stats/summary — dashboard stats
router.get('/stats/summary', auth, async (req, res) => {
  try {
    const userId = req.user._id;
    const [total, done, overdue, pending, anomalies, autoGenerated] = await Promise.all([
      Reminder.countDocuments({ user: userId }),
      Reminder.countDocuments({ user: userId, status: 'Done' }),
      Reminder.countDocuments({ user: userId, status: 'Overdue' }),
      Reminder.countDocuments({ user: userId, status: 'Pending' }),
      Reminder.countDocuments({ user: userId, mlAnomalyFlag: true }),
      Reminder.countDocuments({ user: userId, autoGenerated: true })
    ]);
    res.json({ total, done, overdue, pending, anomalies, autoGenerated });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = router;
