import { get } from '../utils/api.js';
import { loadPage } from './app.js';

export async function renderDashboard(container) {
  try {
    const [statsData, remindersData, mlData] = await Promise.all([
      get('/reminders/stats/summary'),
      get('/reminders'),
      get('/ml/insights')
    ]);

    const { total, done, overdue, pending, anomalies, autoGenerated } = statsData;
    const reminders = remindersData.reminders || [];
    const insights  = mlData.insights || {};
    const pct = total ? Math.round((done / total) * 100) : 0;
    const recent = [...reminders].sort((a,b) => new Date(a.dueDate)-new Date(b.dueDate)).slice(0, 5);
    const user  = JSON.parse(localStorage.getItem('em_user') || '{}');

    container.innerHTML = `
      <div class="anim-fadeup">

        <!-- Hero -->
        <div style="margin-bottom:2rem">
          <div style="display:inline-flex;align-items:center;gap:6px;background:rgba(0,229,255,.08);border:1px solid rgba(0,229,255,.18);color:var(--accent);font-family:var(--fm);font-size:.68rem;padding:4px 12px;border-radius:20px;margin-bottom:1rem;letter-spacing:1px">
            ⚡ SMART MAINTENANCE DASHBOARD
          </div>
          <h1 style="margin-bottom:.5rem">
            Welcome back,
            <span style="background:linear-gradient(90deg,var(--accent),var(--accent3));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text">${user.name || 'User'}</span>
          </h1>
          <p style="color:var(--muted);font-size:.95rem">Your personalised maintenance overview.</p>
        </div>

        <!-- Stats -->
        <div class="stats-grid mb-2 anim-fadeup anim-d1">
          <div class="stat-card">
            <div class="stat-value text-accent">${total}</div>
            <div class="stat-label">Total Tasks</div>
          </div>
          <div class="stat-card">
            <div class="stat-value" style="color:var(--red)">${overdue}</div>
            <div class="stat-label">Overdue</div>
          </div>
          <div class="stat-card">
            <div class="stat-value" style="color:var(--yellow)">${pending}</div>
            <div class="stat-label">Pending</div>
          </div>
          <div class="stat-card">
            <div class="stat-value" style="color:var(--green)">${done}</div>
            <div class="stat-label">Completed</div>
            <div class="progress-outer"><div class="progress-inner" style="width:${pct}%"></div></div>
          </div>
          <div class="stat-card" style="border-color:rgba(0,229,255,.25)">
            <div class="stat-value" style="color:var(--accent);font-size:1.6rem">${autoGenerated || 0}</div>
            <div class="stat-label">🤖 Auto-Generated</div>
          </div>
          <div class="stat-card" style="border-color:rgba(167,139,250,.25)">
            <div class="stat-value" style="color:var(--accent3)">${anomalies}</div>
            <div class="stat-label">ML Anomalies</div>
          </div>
        </div>

        <div class="grid-2 mt-3">

          <!-- Recent reminders -->
          <div>
            <div class="section-header anim-fadeup anim-d2">
              <h2>Recent Reminders <span class="section-title-tag">(${recent.length})</span></h2>
              <button class="btn btn-secondary btn-sm" id="view-all-btn">View All →</button>
            </div>
            <div style="display:flex;flex-direction:column;gap:.6rem" class="anim-fadeup anim-d3">
              ${recent.length ? recent.map(r => reminderMini(r)).join('') : emptyMini('No reminders yet — add a device to get started!')}
            </div>
          </div>

          <!-- ML summary panel -->
          <div>
            <div class="section-header anim-fadeup anim-d2">
              <h2>🤖 ML Insights</h2>
              <button class="btn btn-secondary btn-sm" id="view-ml-btn">Full Report →</button>
            </div>
            <div style="display:flex;flex-direction:column;gap:.75rem" class="anim-fadeup anim-d3">

              <!-- Auto vs manual breakdown -->
              <div class="ml-card">
                <div class="ml-label">📊 Reminder Sources</div>
                <div style="display:flex;gap:1rem;margin-top:.5rem">
                  <div style="flex:1;text-align:center;background:rgba(0,229,255,.07);border-radius:8px;padding:.6rem">
                    <div style="font-family:var(--fm);font-size:1.4rem;font-weight:700;color:var(--accent)">${autoGenerated||0}</div>
                    <div style="font-size:.68rem;color:var(--muted)">🤖 Auto-Generated</div>
                  </div>
                  <div style="flex:1;text-align:center;background:rgba(167,139,250,.07);border-radius:8px;padding:.6rem">
                    <div style="font-family:var(--fm);font-size:1.4rem;font-weight:700;color:var(--accent3)">${total - (autoGenerated||0)}</div>
                    <div style="font-size:.68rem;color:var(--muted)">✋ Manual</div>
                  </div>
                </div>
              </div>

              ${insights.highPriority?.length ? `
              <div class="ml-card">
                <div class="ml-label">⚠ High Priority Tasks</div>
                ${insights.highPriority.slice(0,3).map(r => `
                  <div style="display:flex;align-items:center;justify-content:space-between;padding:5px 0;border-bottom:1px solid rgba(167,139,250,.1)">
                    <span style="font-size:.84rem;font-weight:600">${r.title}</span>
                    <span style="font-family:var(--fm);font-size:.68rem;color:var(--accent3)">${r.mlPriorityScore}/100</span>
                  </div>`).join('')}
              </div>` : ''}

              ${insights.predictions?.length ? `
              <div class="ml-card" style="background:rgba(0,229,255,.05);border-color:rgba(0,229,255,.18)">
                <div class="ml-label" style="color:var(--accent)">📅 Upcoming Predictions</div>
                ${insights.predictions.slice(0,3).map(p => `
                  <div style="display:flex;align-items:center;justify-content:space-between;padding:5px 0;border-bottom:1px solid rgba(0,229,255,.08)">
                    <div>
                      <div style="font-size:.82rem;font-weight:600">${p.title}</div>
                      <div style="font-size:.7rem;color:var(--muted)">${p.device}</div>
                    </div>
                    <div style="text-align:right">
                      <div style="font-family:var(--fm);font-size:.7rem;color:var(--accent)">${formatDate(p.predictedDate)}</div>
                      <div style="font-family:var(--fm);font-size:.62rem;color:var(--muted)">${Math.round((p.confidence||0)*100)}% conf.</div>
                    </div>
                  </div>`).join('')}
              </div>` : ''}

              ${insights.anomalies?.length ? `
              <div class="ml-card" style="background:rgba(255,107,53,.05);border-color:rgba(255,107,53,.2)">
                <div class="ml-label" style="color:var(--accent2)">🚨 ${insights.anomalies.length} Anomaly${insights.anomalies.length>1?'s':''} Detected</div>
                ${insights.anomalies.slice(0,2).map(r => `
                  <div style="padding:4px 0;border-bottom:1px solid rgba(255,107,53,.1)">
                    <div style="font-size:.82rem;font-weight:600">${r.title}</div>
                    <div style="font-size:.7rem;color:var(--accent2);margin-top:2px">${r.mlAnomalyReason?.split(';')[0]}</div>
                  </div>`).join('')}
              </div>` : `
              <div class="ml-card" style="background:rgba(34,197,94,.05);border-color:rgba(34,197,94,.2)">
                <div class="ml-label" style="color:var(--green)">✅ All Clear</div>
                <p style="font-size:.82rem;color:var(--muted);margin-top:4px">No anomalies detected. Great job maintaining your devices!</p>
              </div>`}

              <!-- Avg score ring -->
              <div class="ml-card" style="display:flex;align-items:center;justify-content:space-between">
                <div>
                  <div class="ml-label">Avg Priority Score</div>
                  <div style="font-family:var(--fm);font-size:1.6rem;font-weight:700;color:var(--accent3)">
                    ${insights.avgPriorityScore||0}<span style="font-size:.75rem">/100</span>
                  </div>
                </div>
                <div style="width:60px;height:60px;position:relative">
                  <svg viewBox="0 0 60 60" style="transform:rotate(-90deg)">
                    <circle cx="30" cy="30" r="22" fill="none" stroke="var(--border)" stroke-width="5"/>
                    <circle cx="30" cy="30" r="22" fill="none" stroke="var(--accent3)" stroke-width="5"
                      stroke-dasharray="${2*Math.PI*22}"
                      stroke-dashoffset="${2*Math.PI*22*(1-(insights.avgPriorityScore||0)/100)}"
                      stroke-linecap="round"/>
                  </svg>
                </div>
              </div>

            </div>
          </div>

        </div>
      </div>
    `;

    document.getElementById('view-all-btn').addEventListener('click', () => navTo('reminders'));
    document.getElementById('view-ml-btn').addEventListener('click',  () => navTo('ml'));

  } catch (err) {
    container.innerHTML = `<div class="empty"><div class="empty-icon">⚠</div><p class="empty-text">${err.message}</p></div>`;
  }
}

function navTo(page) {
  window._currentPage = page;
  document.querySelectorAll('.nav-btn').forEach(b => b.classList.toggle('active', b.dataset.page === page));
  loadPage(page);
}

function reminderMini(r) {
  const st = getStatus(r);
  return `
    <div class="reminder-item ${r.status==='Done'?'done':''}">
      <div class="ri-bar ${st}"></div>
      <div>
        <div class="ri-title" style="display:flex;align-items:center;gap:.4rem">
          ${r.title}
          ${r.autoGenerated ? `<span style="font-family:var(--fm);font-size:.58rem;background:rgba(0,229,255,.1);color:var(--accent);border:1px solid rgba(0,229,255,.2);padding:1px 5px;border-radius:3px">AUTO</span>` : ''}
        </div>
        <div class="ri-meta">
          <span class="ri-meta-item">📱 ${r.device?.name||'—'}</span>
          <span class="ri-meta-item">📅 ${formatDate(r.dueDate)}</span>
          <span class="ri-meta-item">⏱ ${daysLabel(r)}</span>
        </div>
      </div>
      <span class="badge badge-${st}">${stLabel(st)}</span>
    </div>`;
}

function emptyMini(msg) {
  return `<div class="empty"><div class="empty-icon">📭</div><p class="empty-text">${msg}</p></div>`;
}

function getStatus(r) {
  if (r.status === 'Done')    return 'done';
  if (r.status === 'Overdue') return 'overdue';
  const diff = (new Date(r.dueDate) - new Date()) / 86400000;
  if (diff <= 3) return 'warning';
  return 'ok';
}

function stLabel(s) {
  return { ok:'Upcoming', warning:'Due Soon', overdue:'OVERDUE', done:'Done' }[s];
}

function daysLabel(r) {
  if (r.status === 'Done') return 'Completed';
  const diff = Math.ceil((new Date(r.dueDate) - new Date()) / 86400000);
  if (diff === 0) return 'Due Today';
  if (diff < 0)  return `${Math.abs(diff)}d overdue`;
  return `in ${diff}d`;
}

function formatDate(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day:'numeric', month:'short', year:'numeric' });
}
