import { get, api } from '../utils/api.js';
import { toast } from '../components/toast.js';

export async function renderMLInsights(container) {
  container.innerHTML = `<div style="display:flex;justify-content:center;padding:3rem"><span class="spinner" style="width:28px;height:28px;border-width:3px"></span></div>`;
  try {
    const [insightsData, remindersData, statsData] = await Promise.all([
      get('/ml/insights'),
      get('/reminders'),
      get('/ml/model-stats').catch(() => ({ stats: null }))
    ]);
    buildMLUI(container, insightsData.insights, remindersData.reminders || [], statsData.stats);
  } catch (err) {
    container.innerHTML = `<div class="empty"><div class="empty-icon">🤖</div><p class="empty-text">${err.message}</p></div>`;
  }
}

function buildMLUI(container, ins, reminders, modelStats) {
  const total     = reminders.length;
  const done      = reminders.filter(r => r.status === 'Done').length;
  const overdue   = reminders.filter(r => r.status === 'Overdue').length;
  const autoGen   = reminders.filter(r => r.autoGenerated).length;
  const rf        = ins.rfInsights || {};

  container.innerHTML = `
  <div class="anim-fadeup">

    <!-- ── Header ── -->
    <div style="margin-bottom:2rem">
      <div style="display:inline-flex;align-items:center;gap:6px;background:rgba(167,139,250,.1);border:1px solid rgba(167,139,250,.25);color:var(--accent3);font-family:var(--fm);font-size:.68rem;padding:4px 12px;border-radius:20px;margin-bottom:1rem;letter-spacing:1px">
        🤖 ML ENGINE v3.0 — DECISION TREE + RANDOM FOREST
      </div>
      <h1 style="margin-bottom:.5rem">ML <span style="background:linear-gradient(90deg,var(--accent3),var(--accent));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text">Insights</span></h1>
      <p style="color:var(--muted);font-size:.92rem">Three real ML models working together on your maintenance data</p>
    </div>

    <!-- ── Model Status Cards ── -->
    <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1rem;margin-bottom:2rem" class="anim-fadeup anim-d1">
      ${modelStatusCard('🌳','Decision Tree','CART Algorithm','Classification + Regression','var(--accent)','Active')}
      ${modelStatusCard('🌲','Random Forest','10 Trees Ensemble','Majority Vote','var(--accent3)','Active')}
      ${modelStatusCard('📈','WMA Predictor','Time Series','Date Forecasting','var(--green)','Active')}
      ${modelStatusCard('🚨','Anomaly Detector','Rule-Based','Pattern Recognition','var(--yellow)','Active')}
    </div>

    <!-- ── Transparency Note ── -->
    <div style="background:rgba(245,158,11,.05);border:1px solid rgba(245,158,11,.2);border-radius:var(--r2);padding:1rem 1.25rem;margin-bottom:2rem">
      <div style="font-family:var(--fm);font-size:.68rem;color:var(--yellow);letter-spacing:1px;margin-bottom:.4rem">📖 HOW THESE MODELS WORK</div>
      <p style="font-size:.8rem;color:var(--text2);line-height:1.7">
        <strong style="color:var(--text)">Decision Tree:</strong> Learns a flowchart of yes/no questions from your data using the CART algorithm and Gini Impurity splitting. Each path through the tree ends in a prediction. &nbsp;
        <strong style="color:var(--text)">Random Forest:</strong> Builds 10 different Decision Trees, each trained on a random sample of data with random feature subsets. Final answer = majority vote across all 10 trees. More accurate than a single tree. &nbsp;
        Both models are trained on real data from your completions + synthetic data on first run. The more tasks you complete, the smarter they get.
      </p>
    </div>

    <!-- ── Stats Row ── -->
    <div class="stats-grid mb-3 anim-fadeup anim-d1">
      <div class="stat-card" style="border-color:rgba(239,68,68,.3)">
        <div class="stat-value" style="color:var(--red)">${rf.criticalCount||0}</div>
        <div class="stat-label">🌲 RF Critical</div>
      </div>
      <div class="stat-card" style="border-color:rgba(245,158,11,.3)">
        <div class="stat-value" style="color:var(--yellow)">${rf.highCount||0}</div>
        <div class="stat-label">🌲 RF High</div>
      </div>
      <div class="stat-card" style="border-color:rgba(167,139,250,.3)">
        <div class="stat-value" style="color:var(--accent3)">${ins.avgPriorityScore||0}</div>
        <div class="stat-label">Avg Score</div>
      </div>
      <div class="stat-card" style="border-color:rgba(255,107,53,.25)">
        <div class="stat-value" style="color:var(--accent2)">${ins.anomalies?.length||0}</div>
        <div class="stat-label">Anomalies</div>
      </div>
      <div class="stat-card" style="border-color:rgba(34,197,94,.25)">
        <div class="stat-value" style="color:var(--green)">${rf.modelAgreement != null ? rf.modelAgreement+'%' : '—'}</div>
        <div class="stat-label">RF↔DT Agreement</div>
      </div>
    </div>

    <!-- ── RF Priority Distribution Chart ── -->
    <div class="grid-2 anim-fadeup anim-d2" style="margin-bottom:2rem">

      <!-- Random Forest distribution bar chart -->
      <div class="card">
        <div style="font-family:var(--fm);font-size:.68rem;color:var(--accent3);letter-spacing:1px;margin-bottom:.85rem">🌲 RANDOM FOREST — PRIORITY DISTRIBUTION</div>
        ${rfBarChart(rf, total - done)}
        <div style="margin-top:.85rem;font-size:.75rem;color:var(--muted)">
          Avg confidence: <strong style="color:var(--text)">${rf.avgConfidence != null ? Math.round(rf.avgConfidence*100)+'%' : 'Pending'}</strong>
          &nbsp;·&nbsp; Predictions made: <strong style="color:var(--text)">${rf.remindersWithPrediction||0}</strong>
        </div>
      </div>

      <!-- Completion + source donut -->
      <div class="card">
        <div style="font-family:var(--fm);font-size:.68rem;color:var(--muted);letter-spacing:1px;margin-bottom:.75rem">COMPLETION OVERVIEW</div>
        <div style="display:flex;align-items:center;gap:1.5rem">
          <div style="position:relative;width:88px;height:88px;flex-shrink:0">
            <svg viewBox="0 0 88 88" style="transform:rotate(-90deg)">
              <circle cx="44" cy="44" r="34" fill="none" stroke="var(--border)" stroke-width="8"/>
              <circle cx="44" cy="44" r="34" fill="none" stroke="var(--green)" stroke-width="8"
                stroke-dasharray="${2*Math.PI*34}"
                stroke-dashoffset="${2*Math.PI*34*(1-(total?done/total:0))}"
                stroke-linecap="round"/>
            </svg>
            <div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center">
              <div style="font-family:var(--fm);font-size:.95rem;font-weight:700;color:var(--green)">${total?Math.round(done/total*100):0}%</div>
              <div style="font-size:.55rem;color:var(--muted)">done</div>
            </div>
          </div>
          <div style="flex:1">
            ${miniBar('✅ Completed',  done,    total, 'var(--green)')}
            ${miniBar('🔴 Overdue',    overdue, total, 'var(--red)')}
            ${miniBar('⏳ Pending',    total-done-overdue, total, 'var(--yellow)')}
            ${miniBar('🤖 Auto-Gen',   autoGen, total, 'var(--accent)')}
          </div>
        </div>
      </div>
    </div>

    <!-- ── How DT + RF Work — Educational Section ── -->
    <div style="margin-bottom:2rem" class="anim-fadeup anim-d2">
      <div style="font-family:var(--fm);font-size:.68rem;color:var(--accent);letter-spacing:1px;margin-bottom:1rem">HOW THE MODELS WORK — STEP BY STEP</div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem">

        <!-- Decision Tree explained -->
        <div style="background:var(--card);border:1px solid var(--border);border-radius:var(--r2);padding:1.25rem">
          <div style="font-size:1.5rem;margin-bottom:.6rem">🌳</div>
          <div style="font-weight:700;margin-bottom:.35rem">Decision Tree (CART)</div>
          <div style="font-family:var(--fm);font-size:.65rem;color:var(--accent);margin-bottom:.75rem">Classification + Regression</div>

          <!-- Visual mini-tree diagram -->
          <div style="background:var(--surface);border-radius:8px;padding:.85rem;font-family:var(--fm);font-size:.65rem;line-height:1.8;color:var(--text2);margin-bottom:.75rem">
            <div style="color:var(--accent);margin-bottom:2px">Device Age &gt; 36mo?</div>
            <div style="padding-left:.75rem">├─ YES → Usage &gt; 8h?</div>
            <div style="padding-left:1.5rem">│ ├─ YES → <span style="color:var(--red)">CRITICAL</span></div>
            <div style="padding-left:1.5rem">│ └─ NO  → <span style="color:var(--yellow)">HIGH</span></div>
            <div style="padding-left:.75rem">└─ NO  → Overdue?</div>
            <div style="padding-left:1.5rem">  ├─ YES → <span style="color:var(--yellow)">HIGH</span></div>
            <div style="padding-left:1.5rem">  └─ NO  → <span style="color:var(--green)">MEDIUM</span></div>
          </div>

          <p style="font-size:.78rem;color:var(--muted);line-height:1.6">
            Splits data at each node using <strong style="color:var(--text)">Gini Impurity</strong> — finds the feature threshold that best separates priority classes. Trains on 8 features extracted from your device and reminder data.
          </p>
        </div>

        <!-- Random Forest explained -->
        <div style="background:var(--card);border:1px solid var(--border);border-radius:var(--r2);padding:1.25rem">
          <div style="font-size:1.5rem;margin-bottom:.6rem">🌲</div>
          <div style="font-weight:700;margin-bottom:.35rem">Random Forest</div>
          <div style="font-family:var(--fm);font-size:.65rem;color:var(--accent3);margin-bottom:.75rem">10-Tree Ensemble — Majority Vote</div>

          <!-- Visual forest diagram -->
          <div style="background:var(--surface);border-radius:8px;padding:.85rem;font-family:var(--fm);font-size:.62rem;line-height:1.7;color:var(--text2);margin-bottom:.75rem">
            <div style="display:grid;grid-template-columns:repeat(5,1fr);gap:4px;margin-bottom:6px">
              ${Array(10).fill(0).map((_, i) => `<div style="background:rgba(167,139,250,.15);border:1px solid rgba(167,139,250,.25);border-radius:4px;padding:3px;text-align:center;font-size:.58rem">T${i+1}</div>`).join('')}
            </div>
            <div style="text-align:center;color:var(--accent3);font-size:.65rem">↓ Majority Vote</div>
            <div style="text-align:center;background:rgba(167,139,250,.15);border-radius:4px;padding:4px;margin-top:4px;color:var(--text)">Final Prediction</div>
          </div>

          <p style="font-size:.78rem;color:var(--muted);line-height:1.6">
            Each tree trains on a <strong style="color:var(--text)">random sample</strong> of data (bootstrap) with random feature subsets. Prevents overfitting. Final answer = class with most votes across all 10 trees.
          </p>
        </div>
      </div>
    </div>

    <!-- ── 8 Features Used ── -->
    <div style="background:var(--card);border:1px solid var(--border);border-radius:var(--r2);padding:1.25rem;margin-bottom:2rem" class="anim-fadeup anim-d2">
      <div style="font-family:var(--fm);font-size:.68rem;color:var(--muted);letter-spacing:1px;margin-bottom:.85rem">8 FEATURES USED BY BOTH MODELS</div>
      <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:.6rem">
        ${[
          ['Category Risk','Vehicle=0.90, Computer=0.85...','How risky the device category is'],
          ['Task Urgency','Replacement=0.95, Battery=0.90...','How critical the task type is'],
          ['Device Age','Normalised 0–1 (max 60 months)','Older devices = higher risk'],
          ['Usage Hours','Normalised 0–1 (max 16 hrs/day)','Heavy use = more wear'],
          ['Days Until Due','Negative=future, Positive=overdue','Urgency from due date'],
          ['Overdue Count','Normalised 0–1 (max 5)','History of neglect'],
          ['Condition Score','Poor=0, Fair=0.33, Good=0.67, Excellent=1','Physical state'],
          ['Warranty Expired','Binary: 0 or 1','No manufacturer safety net'],
        ].map(([name, values, desc]) => `
          <div style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:.75rem">
            <div style="font-family:var(--fm);font-size:.65rem;color:var(--accent3);margin-bottom:3px">${name}</div>
            <div style="font-size:.7rem;color:var(--muted);margin-bottom:3px">${values}</div>
            <div style="font-size:.72rem;color:var(--text2)">${desc}</div>
          </div>`).join('')}
      </div>
    </div>

    <!-- ── Predictions + Anomalies ── -->
    <div class="grid-2 anim-fadeup anim-d3" style="margin-bottom:2rem">
      <div>
        <div class="section-header mb-1"><h2>📅 Date Predictions (WMA)</h2></div>
        <div style="font-size:.75rem;color:var(--muted);margin-bottom:.75rem">From Weighted Moving Average on your completion history</div>
        <div style="display:flex;flex-direction:column;gap:.6rem">
          ${ins.predictions?.length
            ? ins.predictions.map(p => predCard(p)).join('')
            : emptyCard('Complete tasks to activate date predictions')}
        </div>
      </div>
      <div>
        <div class="section-header mb-1"><h2>🚨 Anomaly Report</h2></div>
        <div style="font-size:.75rem;color:var(--muted);margin-bottom:.75rem">Unusual patterns in your maintenance data</div>
        <div style="display:flex;flex-direction:column;gap:.6rem">
          ${ins.anomalies?.length
            ? ins.anomalies.map(a => anomalyCard(a)).join('')
            : `<div class="ml-card" style="background:rgba(34,197,94,.05);border-color:rgba(34,197,94,.2);text-align:center;padding:1.5rem">
                <div style="font-size:1.5rem;margin-bottom:.5rem">✅</div>
                <div style="font-weight:700;color:var(--green)">All Clear!</div>
              </div>`}
        </div>
      </div>
    </div>

    <!-- ── High Priority from RF ── -->
    ${ins.highPriority?.length ? `
    <div class="anim-fadeup anim-d3" style="margin-bottom:2rem">
      <div class="section-header mb-1">
        <h2>⚠ High Priority Tasks <span class="section-title-tag">(RF Score ≥ 75)</span></h2>
      </div>
      <div style="display:flex;flex-direction:column;gap:.6rem">
        ${ins.highPriority.slice(0,8).map(r => priorityCard(r)).join('')}
      </div>
    </div>` : ''}

    <!-- ── Retrain Button ── -->
    <div class="anim-fadeup anim-d4" style="text-align:center;padding:1.5rem 0">
      <button class="btn btn-secondary" id="retrain-btn" style="gap:.5rem">
        🔄 Retrain ML Models with Latest Data
      </button>
      <p style="color:var(--muted);font-size:.75rem;margin-top:.5rem">
        Models auto-retrain every 24 hours. Click to retrain now with your latest completed tasks.
      </p>
    </div>

  </div>`;

  // Retrain button
  document.getElementById('retrain-btn').addEventListener('click', async () => {
    const btn = document.getElementById('retrain-btn');
    btn.innerHTML = '<span class="spinner"></span> Retraining...';
    btn.disabled = true;
    try {
      await api('/ml/retrain', { method: 'POST' });
      toast('✅ Models retrained successfully!', 'success');
      renderMLInsights(container);
    } catch (err) {
      toast(err.message, 'error');
      btn.innerHTML = '🔄 Retrain ML Models';
      btn.disabled = false;
    }
  });
}

// ── Helper components ──────────────────────────────────────────────────────────

function modelStatusCard(icon, name, algo, task, color, status) {
  return `
    <div style="background:var(--card);border:1px solid var(--border);border-radius:var(--r2);padding:1.1rem">
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:.5rem">
        <span style="font-size:1.4rem">${icon}</span>
        <span style="font-family:var(--fm);font-size:.6rem;background:rgba(34,197,94,.12);color:var(--green);border:1px solid rgba(34,197,94,.2);padding:2px 7px;border-radius:10px">${status}</span>
      </div>
      <div style="font-weight:700;font-size:.88rem;margin-bottom:2px">${name}</div>
      <div style="font-family:var(--fm);font-size:.62rem;color:${color};margin-bottom:3px">${algo}</div>
      <div style="font-size:.72rem;color:var(--muted)">${task}</div>
    </div>`;
}

function rfBarChart(rf, activeCount) {
  if (!activeCount) return `<p style="color:var(--muted);font-size:.82rem">Add reminders to see RF predictions.</p>`;
  const bars = [
    { label: 'Critical', count: rf.criticalCount||0, color: 'var(--red)' },
    { label: 'High',     count: rf.highCount||0,     color: 'var(--yellow)' },
    { label: 'Medium',   count: rf.mediumCount||0,   color: 'var(--accent3)' },
    { label: 'Low',      count: rf.lowCount||0,      color: 'var(--green)' },
  ];
  return bars.map(b => {
    const pct = activeCount ? Math.round((b.count / activeCount) * 100) : 0;
    return `
      <div style="margin-bottom:.5rem">
        <div style="display:flex;justify-content:space-between;font-size:.72rem;margin-bottom:3px">
          <span style="color:${b.color};font-weight:700">${b.label}</span>
          <span style="color:var(--text);font-family:var(--fm)">${b.count} (${pct}%)</span>
        </div>
        <div style="height:7px;background:var(--border);border-radius:4px;overflow:hidden">
          <div style="height:100%;width:${pct}%;background:${b.color};border-radius:4px;transition:width .7s ease"></div>
        </div>
      </div>`;
  }).join('');
}

function miniBar(label, value, total, color) {
  const pct = total ? Math.round((value / total) * 100) : 0;
  return `
    <div style="margin-bottom:.4rem">
      <div style="display:flex;justify-content:space-between;font-size:.7rem;margin-bottom:2px">
        <span style="color:var(--muted)">${label}</span>
        <span style="font-family:var(--fm);color:var(--text)">${value} (${pct}%)</span>
      </div>
      <div style="height:4px;background:var(--border);border-radius:2px;overflow:hidden">
        <div style="height:100%;width:${pct}%;background:${color};transition:width .6s"></div>
      </div>
    </div>`;
}

function predCard(p) {
  const conf  = Math.round((p.confidence||0)*100);
  const color = conf >= 80 ? 'var(--green)' : conf >= 60 ? 'var(--yellow)' : 'var(--red)';
  return `
    <div class="ml-card" style="background:rgba(0,229,255,.04);border-color:rgba(0,229,255,.18)">
      <div style="display:flex;justify-content:space-between;align-items:flex-start">
        <div>
          <div style="font-weight:700;font-size:.88rem">${p.title}</div>
          <div style="font-size:.72rem;color:var(--muted);margin-top:2px">${p.device}</div>
        </div>
        <div style="text-align:right;flex-shrink:0;margin-left:1rem">
          <div style="font-family:var(--fm);font-size:.78rem;color:var(--accent)">${formatDate(p.predictedDate)}</div>
          <div style="font-family:var(--fm);font-size:.62rem;color:${color}">${conf}% conf.</div>
        </div>
      </div>
      <div style="margin-top:.5rem;background:var(--border);height:3px;border-radius:2px;overflow:hidden">
        <div style="height:100%;width:${conf}%;background:${color};transition:width .6s"></div>
      </div>
    </div>`;
}

function anomalyCard(a) {
  return `
    <div class="ml-card" style="background:rgba(255,107,53,.05);border-color:rgba(255,107,53,.2)">
      <div style="display:flex;gap:.6rem">
        <span style="flex-shrink:0">⚠</span>
        <div>
          <div style="font-weight:700;font-size:.85rem">${a.title}</div>
          <div style="font-size:.7rem;color:var(--muted);margin-top:2px">${a.device?.name} — ${a.device?.brand}</div>
          ${a.mlAnomalyReason ? `<div style="font-size:.72rem;color:var(--accent2);margin-top:4px;line-height:1.5">${a.mlAnomalyReason.split(';').map(r=>`• ${r.trim()}`).join('<br>')}</div>` : ''}
        </div>
      </div>
    </div>`;
}

function priorityCard(r) {
  const score = r.mlPriorityScore || 0;
  const rfLabel = r.rfPriorityLabel;
  const dtLabel = r.dtPriorityLabel;
  const color = score >= 85 ? 'var(--red)' : score >= 70 ? 'var(--yellow)' : 'var(--accent3)';
  const agree = rfLabel && dtLabel && rfLabel === dtLabel;
  return `
    <div style="background:var(--card);border:1px solid var(--border);border-radius:var(--r2);padding:.85rem 1.1rem;display:flex;align-items:center;gap:.85rem">
      <div style="width:44px;height:44px;flex-shrink:0;position:relative">
        <svg viewBox="0 0 44 44" style="transform:rotate(-90deg)">
          <circle cx="22" cy="22" r="16" fill="none" stroke="var(--border)" stroke-width="4"/>
          <circle cx="22" cy="22" r="16" fill="none" stroke="${color}" stroke-width="4"
            stroke-dasharray="${2*Math.PI*16}"
            stroke-dashoffset="${2*Math.PI*16*(1-score/100)}"
            stroke-linecap="round"/>
        </svg>
        <div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-family:var(--fm);font-size:.6rem;font-weight:700;color:${color}">${score}</div>
      </div>
      <div style="flex:1;min-width:0">
        <div style="font-weight:700;font-size:.88rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${r.title}</div>
        <div style="font-size:.7rem;color:var(--muted);margin-top:2px">${r.device?.name} · ${formatDate(r.dueDate)}</div>
        <div style="display:flex;gap:.4rem;margin-top:4px;flex-wrap:wrap">
          ${rfLabel ? `<span style="font-family:var(--fm);font-size:.6rem;background:rgba(167,139,250,.12);color:var(--accent3);border:1px solid rgba(167,139,250,.2);padding:1px 6px;border-radius:3px">🌲 RF: ${rfLabel}</span>` : ''}
          ${dtLabel ? `<span style="font-family:var(--fm);font-size:.6rem;background:rgba(0,229,255,.1);color:var(--accent);border:1px solid rgba(0,229,255,.2);padding:1px 6px;border-radius:3px">🌳 DT: ${dtLabel}</span>` : ''}
          ${rfLabel && dtLabel ? `<span style="font-family:var(--fm);font-size:.6rem;padding:1px 6px;border-radius:3px;${agree ? 'background:rgba(34,197,94,.1);color:var(--green);border:1px solid rgba(34,197,94,.2)' : 'background:rgba(239,68,68,.1);color:var(--red);border:1px solid rgba(239,68,68,.2)'}">${agree ? '✓ Agree' : '✗ Disagree'}</span>` : ''}
        </div>
      </div>
      <div style="font-family:var(--fm);font-size:.6rem;color:${color};text-transform:uppercase;letter-spacing:.5px;flex-shrink:0">${score>=85?'CRITICAL':score>=70?'HIGH':'ELEVATED'}</div>
    </div>`;
}

function emptyCard(msg) {
  return `<div class="empty"><div class="empty-icon" style="font-size:2rem">🤖</div><p class="empty-text">${msg}</p></div>`;
}

function formatDate(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day:'numeric', month:'short', year:'numeric' });
}
