import { get, post, patch, del } from '../utils/api.js';
import { toast } from '../components/toast.js';
import { showModal, closeModal } from '../components/modal.js';

let allReminders = [];
let activeFilter = 'all';

export async function renderReminders(container) {
  container.innerHTML = `<div style="display:flex;justify-content:center;padding:3rem"><span class="spinner" style="width:28px;height:28px;border-width:3px"></span></div>`;
  try {
    const [remData, devData] = await Promise.all([get('/reminders'), get('/devices')]);
    allReminders = remData.reminders || [];
    buildReminderUI(container, allReminders, devData.devices || []);
  } catch (err) {
    container.innerHTML = `<div class="empty"><div class="empty-icon">⚠</div><p class="empty-text">${err.message}</p></div>`;
  }
}

function buildReminderUI(container, reminders, devices) {
  const autoCount   = reminders.filter(r => r.autoGenerated).length;
  const anomalyList = reminders.filter(r => r.mlAnomalyFlag && r.status !== 'Done');

  container.innerHTML = `
    <div class="anim-fadeup">
      <div class="section-header mb-2">
        <div>
          <h2>Maintenance Reminders <span class="section-title-tag" id="rem-count"></span></h2>
          <p style="color:var(--muted);font-size:.82rem;margin-top:2px">
            ${autoCount} auto-generated · ${reminders.length - autoCount} manual
          </p>
        </div>
        <button class="btn btn-primary" id="add-rem-btn">+ Add Manual Reminder</button>
      </div>

      ${anomalyList.length ? `
      <div style="background:rgba(255,107,53,.07);border:1px solid rgba(255,107,53,.25);border-radius:10px;padding:.85rem 1.1rem;margin-bottom:1.25rem;display:flex;align-items:center;gap:.75rem">
        <span style="font-size:1rem">🤖</span>
        <div>
          <span style="font-size:.82rem;font-weight:700;color:var(--accent2)">ML: ${anomalyList.length} Anomaly${anomalyList.length>1?'s':''} Detected</span>
          <span style="font-size:.75rem;color:var(--muted);margin-left:.6rem">${anomalyList.slice(0,2).map(a=>a.title).join(', ')}${anomalyList.length>2?'...':''}</span>
        </div>
      </div>` : ''}

      <!-- Filter tabs -->
      <div class="tab-bar" id="filter-bar">
        ${[
          ['all','ALL'],['overdue','OVERDUE'],['warning','DUE SOON'],
          ['ok','UPCOMING'],['done','COMPLETED'],['auto','🤖 AUTO-GENERATED']
        ].map(([f,l]) => `<button class="tab-btn ${f===activeFilter?'active':''}" data-filter="${f}">${l}</button>`).join('')}
      </div>

      <div id="rem-list" style="display:flex;flex-direction:column;gap:.6rem"></div>
    </div>`;

  document.getElementById('filter-bar').addEventListener('click', e => {
    const btn = e.target.closest('[data-filter]');
    if (!btn) return;
    activeFilter = btn.dataset.filter;
    document.querySelectorAll('[data-filter]').forEach(b => b.classList.toggle('active', b.dataset.filter === activeFilter));
    renderList();
  });

  document.getElementById('add-rem-btn').addEventListener('click', () => openAddModal(container, devices));
  renderList();

  function renderList() {
    let filtered = allReminders;

    if (activeFilter === 'auto') {
      filtered = allReminders.filter(r => r.autoGenerated);
    } else if (activeFilter !== 'all') {
      filtered = allReminders.filter(r => {
        if (activeFilter === 'done')    return r.status === 'Done';
        if (activeFilter === 'overdue') return r.status === 'Overdue';
        if (activeFilter === 'warning') {
          const d = (new Date(r.dueDate) - new Date()) / 86400000;
          return r.status === 'Pending' && d >= 0 && d <= 3;
        }
        if (activeFilter === 'ok') {
          const d = (new Date(r.dueDate) - new Date()) / 86400000;
          return r.status === 'Pending' && d > 3;
        }
        return true;
      });
    }

    document.getElementById('rem-count').textContent = `(${filtered.length})`;

    const list = document.getElementById('rem-list');
    if (!filtered.length) {
      list.innerHTML = `<div class="empty"><div class="empty-icon">📭</div><p class="empty-text">No reminders for this filter.</p></div>`;
      return;
    }

    filtered.sort((a, b) => {
      if (a.status === 'Done' && b.status !== 'Done') return 1;
      if (a.status !== 'Done' && b.status === 'Done') return -1;
      return new Date(a.dueDate) - new Date(b.dueDate);
    });

    list.innerHTML = filtered.map(r => reminderRow(r)).join('');

    list.querySelectorAll('.rem-done-btn').forEach(btn => {
      btn.addEventListener('click', async () => {
        try {
          await patch(`/reminders/${btn.dataset.id}/complete`);
          toast('✅ Marked as done!', 'success');
          await refreshReminders(container, devices);
        } catch (err) { toast(err.message, 'error'); }
      });
    });

    list.querySelectorAll('.rem-del-btn').forEach(btn => {
      btn.addEventListener('click', async () => {
        if (!confirm('Delete this reminder?')) return;
        try {
          await del(`/reminders/${btn.dataset.id}`);
          toast('Deleted', 'success');
          await refreshReminders(container, devices);
        } catch (err) { toast(err.message, 'error'); }
      });
    });
  }
}

function reminderRow(r) {
  const st = getStatus(r);
  return `
    <div class="reminder-item ${r.status==='Done'?'done':''}">
      <div class="ri-bar ${st}"></div>
      <div style="min-width:0">
        <div class="ri-title" style="display:flex;align-items:center;gap:.4rem;flex-wrap:wrap">
          ${r.title}
          ${r.autoGenerated ? `<span style="font-family:var(--fm);font-size:.58rem;background:rgba(0,229,255,.1);color:var(--accent);border:1px solid rgba(0,229,255,.2);padding:1px 5px;border-radius:3px" title="Auto-generated by Smart Reminder Engine">🤖 AUTO</span>` : ''}
          ${r.mlAnomalyFlag ? `<span class="badge badge-anomaly" style="font-size:.58rem">⚠ ANOMALY</span>` : ''}
        </div>
        <div class="ri-meta">
          <span class="ri-meta-item">📱 ${r.device?.name||'?'} (${r.device?.brand||''})</span>
          <span class="ri-meta-item">📅 ${formatDate(r.dueDate)}</span>
          <span class="ri-meta-item">🔖 ${r.taskType}</span>
          <span class="ri-meta-item">${r.priority==='High'?'🔴':r.priority==='Medium'?'🟡':'🟢'} ${r.priority}</span>
          ${r.mlPriorityScore != null ? `<span class="ri-meta-item" style="color:var(--accent3)">🎯 Score: ${r.mlPriorityScore}/100</span>` : ''}
          ${r.mlPredictedDate ? `<span class="ri-meta-item" style="color:var(--accent)">📈 Predicted: ${formatDate(r.mlPredictedDate)}</span>` : ''}
          <span class="ri-meta-item">⏱ ${daysLabel(r)}</span>
          ${r.repeatEvery > 0 ? `<span class="ri-meta-item" style="color:var(--muted)">🔁 Every ${r.repeatEvery} ${r.repeatUnit}</span>` : ''}
        </div>
        ${r.mlAnomalyReason ? `<div style="font-size:.7rem;color:var(--accent2);margin-top:3px">🤖 ${r.mlAnomalyReason.split(';')[0]}</div>` : ''}
        ${r.description ? `<div style="font-size:.75rem;color:var(--muted);margin-top:3px">${r.description}</div>` : ''}
      </div>
      <span class="badge badge-${st}">${stLabel(st)}</span>
      <div class="ri-actions">
        ${r.status !== 'Done' ? `<button class="btn btn-ghost btn-icon rem-done-btn" data-id="${r._id}" title="Mark Done" style="color:var(--green)">✓</button>` : ''}
        <button class="btn btn-ghost btn-icon rem-del-btn" data-id="${r._id}" title="Delete" style="color:var(--muted)">✕</button>
      </div>
    </div>`;
}

function openAddModal(container, devices) {
  if (!devices.length) { toast('⚠ Please add a device first!', 'warn'); return; }

  const overlay = showModal(`
    <div class="modal-title">➕ Add Manual Reminder</div>
    <div style="display:flex;flex-direction:column;gap:.85rem">
      <div class="form-group">
        <label class="form-label">Task Title *</label>
        <input class="form-input" id="r-title" placeholder="e.g. Check power supply" />
      </div>
      <div class="grid-2">
        <div class="form-group">
          <label class="form-label">Device *</label>
          <select class="form-select" id="r-device">
            ${devices.map(d => `<option value="${d._id}">${d.name} (${d.brand})</option>`).join('')}
          </select>
        </div>
        <div class="form-group">
          <label class="form-label">Task Type</label>
          <select class="form-select" id="r-tasktype">
            ${['Cleaning','Software Update','Hardware Check','Battery Check','Backup','Calibration','Replacement','Inspection','Other'].map(t=>`<option>${t}</option>`).join('')}
          </select>
        </div>
      </div>
      <div class="grid-2">
        <div class="form-group">
          <label class="form-label">Due Date *</label>
          <input class="form-input" id="r-date" type="date" />
        </div>
        <div class="form-group">
          <label class="form-label">Priority</label>
          <select class="form-select" id="r-priority">
            <option value="High">🔴 High</option>
            <option value="Medium" selected>🟡 Medium</option>
            <option value="Low">🟢 Low</option>
          </select>
        </div>
      </div>
      <div class="grid-2">
        <div class="form-group">
          <label class="form-label">Repeat Every (0 = no repeat)</label>
          <input class="form-input" id="r-repeat" type="number" value="0" min="0" />
        </div>
        <div class="form-group">
          <label class="form-label">Repeat Unit</label>
          <select class="form-select" id="r-unit">
            <option value="days">Days</option>
            <option value="weeks">Weeks</option>
            <option value="months">Months</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label class="form-label">Description (optional)</label>
        <textarea class="form-textarea" id="r-desc" placeholder="What needs to be done..."></textarea>
      </div>
      <div style="background:rgba(167,139,250,.07);border:1px solid rgba(167,139,250,.18);border-radius:8px;padding:.7rem;font-size:.76rem;color:var(--accent3)">
        🤖 ML analysis (priority score, date prediction, anomaly check) runs automatically after saving.
      </div>
      <div id="r-error" style="color:var(--red);font-size:.8rem;display:none"></div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" id="r-cancel">Cancel</button>
      <button class="btn btn-primary" id="r-save">Save & Analyse</button>
    </div>`);

  overlay.querySelector('#r-date').valueAsDate = new Date();
  overlay.querySelector('#r-cancel').addEventListener('click', () => closeModal(overlay));
  overlay.querySelector('#r-save').addEventListener('click', async () => {
    const btn = overlay.querySelector('#r-save');
    const errEl = overlay.querySelector('#r-error');
    errEl.style.display = 'none';
    btn.innerHTML = '<span class="spinner"></span> Saving...';
    btn.disabled = true;
    try {
      await post('/reminders', {
        title:       overlay.querySelector('#r-title').value,
        device:      overlay.querySelector('#r-device').value,
        taskType:    overlay.querySelector('#r-tasktype').value,
        dueDate:     overlay.querySelector('#r-date').value,
        priority:    overlay.querySelector('#r-priority').value,
        repeatEvery: parseInt(overlay.querySelector('#r-repeat').value)||0,
        repeatUnit:  overlay.querySelector('#r-unit').value,
        description: overlay.querySelector('#r-desc').value
      });
      closeModal(overlay);
      toast('✅ Reminder saved & ML analysis complete!', 'success');
      await refreshReminders(container, devices);
    } catch (err) {
      errEl.textContent = err.message; errEl.style.display = 'block';
      btn.innerHTML = 'Save & Analyse'; btn.disabled = false;
    }
  });
}

async function refreshReminders(container, devices) {
  const { reminders } = await get('/reminders');
  allReminders = reminders;
  buildReminderUI(container, reminders, devices);
}

function getStatus(r) {
  if (r.status === 'Done')    return 'done';
  if (r.status === 'Overdue') return 'overdue';
  const diff = (new Date(r.dueDate) - new Date()) / 86400000;
  return diff <= 3 ? 'warning' : 'ok';
}

function stLabel(s) {
  return { ok:'Upcoming', warning:'Due Soon', overdue:'OVERDUE', done:'Done' }[s];
}

function daysLabel(r) {
  if (r.status === 'Done') return 'Completed';
  const diff = Math.ceil((new Date(r.dueDate) - new Date()) / 86400000);
  if (diff === 0) return 'Due Today';
  if (diff < 0)  return `${Math.abs(diff)}d overdue`;
  return `in ${diff}d`;
}

function formatDate(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day:'numeric', month:'short', year:'numeric' });
}
