const mongoose = require('mongoose');

const ReminderSchema = new mongoose.Schema({
  user:   { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  device: { type: mongoose.Schema.Types.ObjectId, ref: 'Device', required: true },
  title:       { type: String, required: true, trim: true },
  description: { type: String, default: '' },
  taskType: {
    type: String,
    enum: ['Cleaning','Software Update','Hardware Check','Battery Check',
           'Backup','Calibration','Replacement','Inspection','Other'],
    default: 'Other'
  },
  priority:   { type: String, enum: ['High','Medium','Low'], default: 'Medium' },
  dueDate:    { type: Date, required: true },
  repeatEvery:{ type: Number, default: 0 },
  repeatUnit: { type: String, enum: ['days','weeks','months'], default: 'days' },
  status:     { type: String, enum: ['Pending','Done','Skipped','Overdue'], default: 'Pending' },
  completedAt:{ type: Date },
  emailSent:  { type: Boolean, default: false },
  autoGenerated: { type: Boolean, default: false },
  source: { type: String, enum: ['manual','knowledge_base','ai_generated'], default: 'manual' },

  // ── v2 ML fields ──
  mlPredictedDate:  { type: Date },
  mlConfidence:     { type: Number },
  mlPriorityScore:  { type: Number },
  mlAnomalyFlag:    { type: Boolean, default: false },
  mlAnomalyReason:  { type: String, default: '' },

  // ── v3 NEW: Decision Tree + Random Forest fields ──
  rfPriorityLabel:  { type: String, enum: ['Critical','High','Medium','Low',null], default: null },
  rfConfidence:     { type: Number, default: null },   // 0.0 – 1.0
  dtPriorityLabel:  { type: String, enum: ['Critical','High','Medium','Low',null], default: null },
  mlIntervalDays:   { type: Number, default: null },   // DT-predicted interval

  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

ReminderSchema.pre('save', function(next) {
  if (this.status === 'Pending') {
    const today = new Date(); today.setHours(0,0,0,0);
    const due   = new Date(this.dueDate); due.setHours(0,0,0,0);
    if (due < today) this.status = 'Overdue';
  }
  this.updatedAt = new Date();
  next();
});

module.exports = mongoose.model('Reminder', ReminderSchema);
